Repository muhilkennedy/Learning-App, pull requests merged in 2020-04, with the labels that each got.

#13 JWT and mailing
  ParentWorkspace/SpringModule/pom.xml
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/config/SecurityConfiguration.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/config/SecurityFilter.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/controller/BaseController.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/controller/CommonController.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/controller/SocialController.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/controller/UserController.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/messages/GenericResponse.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/messages/JWTResponse.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/model/User.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/project/ProjectApplication.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/scheduledTasks/VerificationTask.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/service/LoginService.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/service/VerificationService.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/serviceImpl/LoginServiceImpl.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/serviceImpl/VerificationServiceImpl.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/util/CommonUtil.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/util/ConfigUtil.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/util/JWTUtil.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/util/SocialUtil.java
  ParentWorkspace/SpringModule/src/main/resources/application.properties
Labels: feature, muhil

#25 login related functionalities
  ParentWorkspace/AngularModule/src/app/app-routing.module.ts
  ParentWorkspace/AngularModule/src/app/app.module.ts
  ParentWorkspace/AngularModule/src/app/components/redirect/redirect.component.css
  ParentWorkspace/AngularModule/src/app/components/redirect/redirect.component.html
  ParentWorkspace/AngularModule/src/app/components/redirect/redirect.component.spec.ts
  ParentWorkspace/AngularModule/src/app/components/redirect/redirect.component.ts
  ParentWorkspace/AngularModule/src/app/shared/components/dialog-overview/dialog-overview.component.css
  ParentWorkspace/AngularModule/src/app/shared/components/dialog-overview/dialog-overview.component.html
  ParentWorkspace/AngularModule/src/app/shared/components/dialog-overview/dialog-overview.component.ts
  ParentWorkspace/AngularModule/src/app/shared/services/login.service.ts
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/controller/BaseController.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/controller/SocialController.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/controller/UserController.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/service/FacebookService.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/service/LoginService.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/service/VerificationService.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/serviceImpl/FacebookServiceImpl.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/serviceImpl/GooleServiceImpl.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/serviceImpl/LoginServiceImpl.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/serviceImpl/VerificationServiceImpl.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/util/CommonUtil.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/util/ConfigUtil.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/util/SocialUtil.java
  ParentWorkspace/SpringModule/src/main/resources/application.properties
Labels: ER, muhil

#38 Entity tables
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/model/Cart.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/model/Invoice.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/model/Item.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/model/Orderdetail.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/model/Orders.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/repository/CartRepository.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/repository/ItemRepository.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/repository/OrdersRepository.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/service/ItemService.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/service/OrdersService.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/serviceImpl/ItemServiceImpl.java
  ParentWorkspace/SpringModule/src/main/java/com/miniproject/serviceImpl/OrdersServiceImpl.java
  ParentWorkspace/SpringModule/src/main/resources/database.properties
  ParentWorkspace/SpringModule/src/main/resources/db/migration/V1__initial.sql
Labels: ER, mohan
